"""files model create

Revision ID: f03e102f4639
Revises: 7f1f83e41d04
Create Date: 2025-02-04 08:39:00.788847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03e102f4639'
down_revision = '7f1f83e41d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('subjects_uuid', sa.Uuid(), nullable=False),
    sa.Column('groups_uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['groups_uuid'], ['groups.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subjects_uuid'], ['subjects.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
